<?php

declare(strict_types=1);

namespace YogCloud\Framework\Command;

use Hyperf\Command\Annotation\Command;
use Hyperf\Command\Command as HyperfCommand;
use Psr\Container\ContainerInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;

/**
 * @Command
 */
#[Command]
class ControllerCommand extends HyperfCommand
{
    use CommandTrait;

    protected ContainerInterface $container;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;

        parent::__construct('fs:controller');
    }

    public function configure()
    {
        parent::configure();
        $this->setDescription('Generate controller, Generated by default in app/Controller');
        $this->addOption(
            'force',
            'f',
            InputOption::VALUE_OPTIONAL,
            'Whether to force coverage',
            false
        );
        $this->addOption(
            'path',
            'ap',
            InputOption::VALUE_OPTIONAL,
            'Controller folder path',
            'app/Controller'
        );

        $this->addArgument('class', InputArgument::OPTIONAL, 'class name', false);
    }

    public function handle()
    {
        // path
        $dirPath = $this->input->getOption('path');
        // name
        $name = $this->input->getArgument('class');

        $this->createController($name, $dirPath);
    }

    /**
     * Create a resource controller.
     * @param string $name name
     * @param string $dirPath path
     */
    protected function createController(string $name, string $dirPath): void
    {
        $dirPath .= '/' . $name;
        $nameSpace = ucfirst(str_replace('/', '\\', $dirPath));
        $nameSpace = substr($nameSpace, 0, strlen($nameSpace) - strlen($name) - 1);
        $stub      = file_get_contents(__DIR__ . '/stubs/Controller.stub');

        $serviceFile = BASE_PATH . '/' . $dirPath . '.php';

        $fileContent = str_replace(
            ['#NAMESPACE#', '#ControllerN#'],
            [$nameSpace, $name],
            $stub
        );
        $this->doTouch($serviceFile, $fileContent);
    }
}
