<?php

declare(strict_types=1);

namespace YogCloud\Framework\Command;

use Hyperf\Command\Annotation\Command;
use Hyperf\Command\Command as HyperfCommand;
use Psr\Container\ContainerInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;

/**
 * @Command
 */
#[Command]
class RequestCommand extends HyperfCommand
{
    use CommandTrait;

    protected ContainerInterface $container;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;

        parent::__construct('fs:request');
    }

    public function configure()
    {
        parent::configure();
        $this->setDescription('Generate request, Generated by default in app/Request');
        $this->addOption(
            'force',
            'f',
            InputOption::VALUE_OPTIONAL,
            'Whether to force coverage',
            false
        );
        $this->addOption(
            'path',
            'ap',
            InputOption::VALUE_OPTIONAL,
            'Validator folder path',
            'app/Request'
        );

        $this->addArgument('class', InputArgument::OPTIONAL, 'Class name', false);
    }

    public function handle()
    {
        // path
        $dirPath = $this->input->getOption('path');
        // name
        $name = $this->input->getArgument('class');

        $this->createActions($name, $dirPath);
    }

    /**
     * Create validator.
     * @param string $name name
     * @param string $dirPath path
     */
    protected function createActions(string $name, string $dirPath): void
    {
        $name         = str_replace('\\', '/', $name);
        $stub         = file_get_contents(__DIR__ . '/stubs/Request.stub');
        $serviceFile  = BASE_PATH . '/' . $dirPath . '/' . $name . '.php';
        $requestSpace = ucfirst(str_replace('/', '\\', $dirPath));

        $fileContent = str_replace(
            ['#NAMESPACE#', '#REQUEST#'],
            [$requestSpace, $name],
            $stub
        );
        $this->doTouch($serviceFile, $fileContent);
    }
}
