<?php

declare(strict_types=1);

namespace YogCloud\Framework\Command;

use Hyperf\Command\Annotation\Command;
use Hyperf\Command\Command as HyperfCommand;
use Psr\Container\ContainerInterface;

/**
 * @Command
 */
class ServiceInterfaceCommand extends HyperfCommand
{
    use CommandTrait;

    protected ContainerInterface $container;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;

        parent::__construct('fs:serviceInterface');
    }

    public function configure()
    {
        parent::configure();
        $this->setDescription('Generate service interface, Generated by default in app/Service');
        $this->configureTrait();
    }

    public function handle()
    {
        // getConfig
        [$models, $path] = $this->stubConfig();

        $this->createInterface($models, $path);
    }

    /**
     * Create a service contract from a model.
     */
    protected function createInterface(array $models, string $modelPath): void
    {
        $interfaceSpace = ucfirst(str_replace(['/', 'Model'], ['\\', 'Service'], $modelPath));
        $interfacePath  = str_replace('Model', 'Service', $modelPath);

        $stub = file_get_contents(__DIR__ . '/stubs/ServiceInterface.stub');

        foreach ($models as $model) {
            $interface   = $model . 'ServiceInterface';
            $serviceFile = BASE_PATH . '/' . $interfacePath . '/' . $interface . '.php';
            $fileContent = str_replace(
                ['#INTERFACE#', '#INTERFACE_NAMESPACE#'],
                [$interface, $interfaceSpace],
                $stub
            );
            $this->doTouch($serviceFile, $fileContent);
        }
    }
}
